<?php

// $Id$

/**
 * @file 
 */

/**
 * Implementation of hook_menu()
 */
function terminal_menu() {
  $items = array();
  $items['terminal'] = array(
    'page callback' => 'terminal_ajax_callback',
    //'page arguments' => array(),
    'access arguments' => array('access terminal'),
  );

  return $items;
}

/**
 * Implementation of hook_perm()
 */
function terminal_perm() {
  return array('access terminal');
}

/**
 * Implementation of hook_init()
 */
function terminal_init() {
  drupal_add_js(drupal_get_path('module', 'terminal') .'/terminal.js');
  drupal_add_js(drupal_get_path('module', 'terminal') .'/jquery.terminal.js');
  global $user;
  $host = $_SERVER['host'];
  $settings = array(
    'user' => $user->name,
    'host' => $host,
    'sitename' => variable_get('site_name', ''),
  );
  drupal_add_js($settings, 'setting');
}

function terminal_ajax_callback() {
  $input = $_POST['input'];
  terminal_log_history($input);

  $args = explode(" ", $input);
  $command = array_shift($args);
  switch ($command) {
  case 'adduser':
    terminal_adduser($args);
    break;
  case 'goto':
    terminal_goto($args);
    break;
  case 'nodedel':
    terminal_nodedel($args);
    break;
  }

  exit;
}

function terminal_nodedel($args) {
  $nid = $args[0];
  $node = node_load($nid);
  node_delete($nid);
  print t('Node @title deleted', array('@title' => $node->title));
}

function terminal_goto($args) {
  $path = $args[0];
  print $path;
}

function terminal_adduser($args) {
}

function terminal_log_history($input) {
  global $user;
  //db_query('INSERT INTO {terminal_history} (uid, input) VALUES (%d, "%s")', $input, $user->uid);
}
