<?php
// $Id$

function terminal_install() {
  switch ($GLOBALS['db_type']) {
  case 'mysql':
  case 'mysqli':
    db_query("CREATE TABLE {terminal_history} (
      uid int(10) unsigned NOT NULL default '0',
      input varchar(256) NOT NULL default '',
    ) /*!40100 DEFAULT CHARACTER SET utf8 */;");
    break;
  }
}

function terminal_uninstall() {
  db_query('DROP TABLE {terminal_history}');
}

