<?php

// $Id$

/**
 * @file 
 */

/**
 * Implementation of hook_menu()
 */
function terminal_menu() {
  $items = array();
  $items['terminal'] = array(
    'page callback' => 'terminal_ajax_callback',
    //'page arguments' => array(),
    'access arguments' => array('access terminal'),
  );

  return $items;
}

/**
 * Implementation of hook_perm()
 */
function terminal_perm() {
  return array('access terminal');
}

/**
 * Implementation of hook_init()
 */
function terminal_init() {
  drupal_add_js(drupal_get_path('module', 'terminal') .'/terminal.js');
  drupal_add_js(drupal_get_path('module', 'terminal') .'/jquery.terminal.js');
  global $user;
  $host = $_SERVER['host'];
  $settings = array(
    'user' => $user->name,
    'host' => $host,
    'sitename' => variable_get('site_name', ''),
  );
  drupal_add_js($settings, 'setting');
}

function terminal_ajax_callback() {
  $input = $_POST['input'];
  $args = explode(" ", $input);
  $command = array_shift($args);
  switch ($command) {
  case 'adduser':
    terminal_adduser($args);
    break;
  }

  exit;
}

function terminal_adduser($args) {
}
